"""authentication operations

Revision ID: 06e592667402
Revises: 708efe1d1ac9
Create Date: 2026-09-01 16:57:12.683912

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06e592667402'
down_revision: Union[str, Sequence[str], None] = '708efe1d1ac9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('auth_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_auth_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_auth_events_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_auth_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_auth_events_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('user_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ip_address', sa.String(length=64), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('user_agent', sa.String(length=500), nullable=False, server_default=''))
        batch_op.alter_column('ip_address', server_default=None)
        batch_op.alter_column('user_agent', server_default=None)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_sessions', schema=None) as batch_op:
        batch_op.drop_column('user_agent')
        batch_op.drop_column('ip_address')

    with op.batch_alter_table('auth_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_auth_events_user_id'))
        batch_op.drop_index(batch_op.f('ix_auth_events_event_type'))
        batch_op.drop_index(batch_op.f('ix_auth_events_email'))
        batch_op.drop_index(batch_op.f('ix_auth_events_created_at'))

    op.drop_table('auth_events')
    # ### end Alembic commands ###
