"""asset dns records

Revision ID: 13b7ae191233
Revises: e79782b636c9
Create Date: 2026-09-01 17:36:27.737003

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13b7ae191233'
down_revision: Union[str, Sequence[str], None] = 'e79782b636c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dns_records', sa.JSON(), nullable=False, server_default='{}'))
        batch_op.alter_column('dns_records', server_default=None)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.drop_column('dns_records')

    # ### end Alembic commands ###
