"""endpoint inventory

Revision ID: 1e8f1c89ec54
Revises: bf47a9f6a765
Create Date: 2026-09-02 08:26:22.455384

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e8f1c89ec54'
down_revision: Union[str, Sequence[str], None] = 'bf47a9f6a765'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crawl_rejections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=2000), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('crawl_rejections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_crawl_rejections_project_id'), ['project_id'], unique=False)

    op.create_table('discovered_endpoints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=2000), nullable=False),
    sa.Column('normalized_url', sa.String(length=2000), nullable=False),
    sa.Column('hostname', sa.String(length=255), nullable=False),
    sa.Column('path', sa.String(length=1500), nullable=False),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('query_parameters', sa.JSON(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('content_type', sa.String(length=255), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'normalized_url', name='uq_endpoint_project_url')
    )
    with op.batch_alter_table('discovered_endpoints', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_discovered_endpoints_hostname'), ['hostname'], unique=False)
        batch_op.create_index(batch_op.f('ix_discovered_endpoints_project_id'), ['project_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('discovered_endpoints', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_discovered_endpoints_project_id'))
        batch_op.drop_index(batch_op.f('ix_discovered_endpoints_hostname'))

    op.drop_table('discovered_endpoints')
    with op.batch_alter_table('crawl_rejections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_crawl_rejections_project_id'))

    op.drop_table('crawl_rejections')
    # ### end Alembic commands ###
