"""method aware endpoint inventory

Revision ID: 2272e4cfa37d
Revises: 92f9c600d1a1
Create Date: 2026-09-02 08:51:19.815306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2272e4cfa37d'
down_revision: Union[str, Sequence[str], None] = '92f9c600d1a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('discovered_endpoints', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_endpoint_project_url'), type_='unique')
        batch_op.create_unique_constraint('uq_endpoint_project_url_method', ['project_id', 'normalized_url', 'method'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # The previous schema could retain only one method per normalized URL.
    # Keep the oldest record deterministically before restoring that constraint.
    op.execute(sa.text(
        "DELETE FROM discovered_endpoints WHERE id NOT IN ("
        "SELECT MIN(id) FROM discovered_endpoints GROUP BY project_id, normalized_url)"
    ))
    with op.batch_alter_table('discovered_endpoints', schema=None) as batch_op:
        batch_op.drop_constraint('uq_endpoint_project_url_method', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_endpoint_project_url'), ['project_id', 'normalized_url'])

    # ### end Alembic commands ###
