"""endpoint operation intelligence

Revision ID: 4930f6974b49
Revises: 2272e4cfa37d
Create Date: 2026-09-02 13:37:16.566552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4930f6974b49'
down_revision: Union[str, Sequence[str], None] = '2272e4cfa37d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('discovered_endpoints', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parameter_details', sa.JSON(), nullable=False, server_default=sa.text("'[]'")))
        batch_op.add_column(sa.Column('request_body_content_types', sa.JSON(), nullable=False, server_default=sa.text("'[]'")))
        batch_op.add_column(sa.Column('security_requirements', sa.JSON(), nullable=False, server_default=sa.text("'[]'")))
        batch_op.add_column(sa.Column('tags', sa.JSON(), nullable=False, server_default=sa.text("'[]'")))
        batch_op.add_column(sa.Column('operation_id', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('summary', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('deprecated', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('request_template', sa.JSON(), nullable=False, server_default=sa.text("'{}'")))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('discovered_endpoints', schema=None) as batch_op:
        batch_op.drop_column('request_template')
        batch_op.drop_column('deprecated')
        batch_op.drop_column('summary')
        batch_op.drop_column('operation_id')
        batch_op.drop_column('tags')
        batch_op.drop_column('security_requirements')
        batch_op.drop_column('request_body_content_types')
        batch_op.drop_column('parameter_details')

    # ### end Alembic commands ###
