"""baseline schema

Revision ID: 708efe1d1ac9
Revises: 
Create Date: 2026-09-01 16:47:55.893235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.core.encrypted_types


# revision identifiers, used by Alembic.
revision: str = '708efe1d1ac9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=512), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('target', sa.String(length=255), nullable=False),
    sa.Column('allowed_domains', sa.JSON(), nullable=False),
    sa.Column('allowed_subdomains', sa.JSON(), nullable=False),
    sa.Column('excluded_assets', sa.JSON(), nullable=False),
    sa.Column('program_rules', sa.Text(), nullable=False),
    sa.Column('testing_restrictions', sa.Text(), nullable=False),
    sa.Column('rate_limit_rps', sa.Float(), nullable=False),
    sa.Column('mode', sa.Enum('GUIDED', 'STANDARD', 'ADVANCED', name='huntmode'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'PAUSED', 'ARCHIVED', name='projectstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_projects_owner_id'), ['owner_id'], unique=False)

    op.create_table('user_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('csrf_token', sa.String(length=128), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_sessions_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_sessions_token_hash'), ['token_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('hostname', sa.String(length=255), nullable=False),
    sa.Column('asset_type', sa.Enum('SUBDOMAIN', 'HOST', 'URL', 'API', 'JAVASCRIPT', name='assettype'), nullable=False),
    sa.Column('source', sa.Enum('CRTSH', 'DNS', 'MANUAL', name='assetsource'), nullable=False),
    sa.Column('resolved_ip', sa.String(length=64), nullable=True),
    sa.Column('is_live', sa.Boolean(), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('server_header', sa.String(length=255), nullable=True),
    sa.Column('page_title', sa.String(length=500), nullable=True),
    sa.Column('technologies', sa.JSON(), nullable=False),
    sa.Column('priority_score', sa.Integer(), nullable=False),
    sa.Column('priority_reasons', sa.JSON(), nullable=False),
    sa.Column('priority_category', sa.String(length=64), nullable=True),
    sa.Column('recommended_action', sa.Text(), nullable=True),
    sa.Column('reviewed', sa.Boolean(), nullable=False),
    sa.Column('discovered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assets_hostname'), ['hostname'], unique=False)
        batch_op.create_index(batch_op.f('ix_assets_project_id'), ['project_id'], unique=False)

    op.create_table('http_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('url', sa.String(length=2000), nullable=False),
    sa.Column('request_headers', app.core.encrypted_types.EncryptedJSON(), nullable=False),
    sa.Column('request_body', app.core.encrypted_types.EncryptedText(), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('response_headers', app.core.encrypted_types.EncryptedJSON(), nullable=False),
    sa.Column('response_cookies', app.core.encrypted_types.EncryptedJSON(), nullable=False),
    sa.Column('response_body', app.core.encrypted_types.EncryptedText(), nullable=True),
    sa.Column('response_body_truncated', sa.Boolean(), nullable=False),
    sa.Column('response_size_bytes', sa.Integer(), nullable=True),
    sa.Column('timing_ms', sa.Float(), nullable=True),
    sa.Column('technologies', sa.JSON(), nullable=False),
    sa.Column('interesting_indicators', sa.JSON(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('http_transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_http_transactions_project_id'), ['project_id'], unique=False)

    op.create_table('investigations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('target', sa.String(length=500), nullable=False),
    sa.Column('endpoint', sa.String(length=500), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'FALSE_POSITIVE', 'VALIDATED', 'CLOSED', name='investigationstatus'), nullable=False),
    sa.Column('source', sa.Enum('ASSET', 'ANALYZER_FINDING', 'DIFF_RESULT', 'MANUAL', name='investigationsource'), nullable=False),
    sa.Column('source_reference', sa.JSON(), nullable=False),
    sa.Column('ai_notes', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Integer(), nullable=False),
    sa.Column('linked_transaction_ids', sa.JSON(), nullable=False),
    sa.Column('linked_asset_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('false_positive_checklist', sa.JSON(), nullable=False),
    sa.Column('impact_observed', sa.Text(), nullable=False),
    sa.Column('impact_potential', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('investigations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_investigations_project_id'), ['project_id'], unique=False)

    op.create_table('js_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=2000), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('js_files', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_js_files_project_id'), ['project_id'], unique=False)

    op.create_table('recon_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'BLOCKED', name='reconjobstatus'), nullable=False),
    sa.Column('stage', sa.Enum('SUBDOMAIN_DISCOVERY', 'DNS_RESOLUTION', 'LIVE_HOST_PROBING', 'TECHNOLOGY_DETECTION', 'PRIORITIZATION', 'DONE', name='reconstage'), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('summary', sa.JSON(), nullable=False),
    sa.Column('notes', sa.JSON(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recon_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recon_jobs_project_id'), ['project_id'], unique=False)

    op.create_table('scope_audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('target_input', sa.String(length=500), nullable=False),
    sa.Column('normalized_target', sa.String(length=255), nullable=False),
    sa.Column('decision', sa.Enum('ALLOWED', 'BLOCKED', 'MANUAL_REVIEW', name='scopedecision'), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('operation', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scope_audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scope_audit_logs_project_id'), ['project_id'], unique=False)

    op.create_table('evidence_attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('investigation_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('caption', sa.Text(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evidence_attachments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evidence_attachments_investigation_id'), ['investigation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_attachments_project_id'), ['project_id'], unique=False)

    op.create_table('js_findings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('js_file_id', sa.Integer(), nullable=False),
    sa.Column('finding_type', sa.Enum('API_ROUTE', 'GRAPHQL_URL', 'WEBSOCKET_URL', 'CONFIG_REFERENCE', 'SOURCE_MAP', 'POTENTIAL_SECRET', name='findingtype'), nullable=False),
    sa.Column('value', sa.String(length=2000), nullable=False),
    sa.Column('context', sa.String(length=300), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['js_file_id'], ['js_files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('js_findings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_js_findings_js_file_id'), ['js_file_id'], unique=False)

    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('investigation_id', sa.Integer(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('prerequisites', sa.Text(), nullable=False),
    sa.Column('steps_to_reproduce', sa.Text(), nullable=False),
    sa.Column('observed_behavior', sa.Text(), nullable=False),
    sa.Column('expected_behavior', sa.Text(), nullable=False),
    sa.Column('suggested_remediation', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('investigation_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reports')
    with op.batch_alter_table('js_findings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_js_findings_js_file_id'))

    op.drop_table('js_findings')
    with op.batch_alter_table('evidence_attachments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evidence_attachments_project_id'))
        batch_op.drop_index(batch_op.f('ix_evidence_attachments_investigation_id'))

    op.drop_table('evidence_attachments')
    with op.batch_alter_table('scope_audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scope_audit_logs_project_id'))

    op.drop_table('scope_audit_logs')
    with op.batch_alter_table('recon_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recon_jobs_project_id'))

    op.drop_table('recon_jobs')
    with op.batch_alter_table('js_files', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_js_files_project_id'))

    op.drop_table('js_files')
    with op.batch_alter_table('investigations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_investigations_project_id'))

    op.drop_table('investigations')
    with op.batch_alter_table('http_transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_http_transactions_project_id'))

    op.drop_table('http_transactions')
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assets_project_id'))
        batch_op.drop_index(batch_op.f('ix_assets_hostname'))

    op.drop_table('assets')
    with op.batch_alter_table('user_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_sessions_token_hash'))
        batch_op.drop_index(batch_op.f('ix_user_sessions_expires_at'))

    op.drop_table('user_sessions')
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projects_owner_id'))

    op.drop_table('projects')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
