"""controlled identity profiles

Revision ID: 72df2fc4ce8f
Revises: 4930f6974b49
Create Date: 2026-09-02 14:00:10.776986

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72df2fc4ce8f'
down_revision: Union[str, Sequence[str], None] = '4930f6974b49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('identity_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('identity_key', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    # EncryptedJSON persists ciphertext in a regular TEXT column. Keeping the
    # migration storage-level avoids coupling historical migrations to app code.
    sa.Column('secret_headers', sa.Text(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('identity_key'),
    sa.UniqueConstraint('project_id', 'name', name='uq_identity_project_name')
    )
    with op.batch_alter_table('identity_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_identity_profiles_project_id'), ['project_id'], unique=False)

    with op.batch_alter_table('http_transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('identity_profile_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('identity_profile_key', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('identity_profile_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('profile_header_names', sa.JSON(), nullable=False, server_default='[]'))
        batch_op.create_index(batch_op.f('ix_http_transactions_identity_profile_id'), ['identity_profile_id'], unique=False)
        batch_op.create_foreign_key(
            'fk_http_transactions_identity_profile_id',
            'identity_profiles',
            ['identity_profile_id'],
            ['id'],
            ondelete='SET NULL',
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('http_transactions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_http_transactions_identity_profile_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_http_transactions_identity_profile_id'))
        batch_op.drop_column('profile_header_names')
        batch_op.drop_column('identity_profile_name')
        batch_op.drop_column('identity_profile_key')
        batch_op.drop_column('identity_profile_id')

    with op.batch_alter_table('identity_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_identity_profiles_project_id'))

    op.drop_table('identity_profiles')
    # ### end Alembic commands ###
