"""access control scenarios

Revision ID: 73eb7f3ce327
Revises: 72df2fc4ce8f
Create Date: 2026-09-02 19:11:07.001174

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73eb7f3ce327'
down_revision: Union[str, Sequence[str], None] = '72df2fc4ce8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access_control_scenarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('transaction_ids', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'name', name='uq_access_scenario_project_name')
    )
    with op.batch_alter_table('access_control_scenarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_access_control_scenarios_project_id'), ['project_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('access_control_scenarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_access_control_scenarios_project_id'))

    op.drop_table('access_control_scenarios')
    # ### end Alembic commands ###
