"""public metadata documents

Revision ID: 92f9c600d1a1
Revises: 1e8f1c89ec54
Create Date: 2026-09-02 08:41:54.681875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92f9c600d1a1'
down_revision: Union[str, Sequence[str], None] = '1e8f1c89ec54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('public_metadata_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=2000), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('content_type', sa.String(length=255), nullable=True),
    sa.Column('content_sha256', sa.String(length=64), nullable=True),
    sa.Column('entries', sa.JSON(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'url', name='uq_metadata_project_url')
    )
    with op.batch_alter_table('public_metadata_documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_public_metadata_documents_project_id'), ['project_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('public_metadata_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_public_metadata_documents_project_id'))

    op.drop_table('public_metadata_documents')
    # ### end Alembic commands ###
