"""asset probe source

Revision ID: bf47a9f6a765
Revises: 13b7ae191233
Create Date: 2026-09-01 17:44:34.877514

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf47a9f6a765'
down_revision: Union[str, Sequence[str], None] = '13b7ae191233'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('probe_source', sa.String(length=50), nullable=False, server_default='vajra-httpx'))
        batch_op.alter_column('probe_source', server_default=None)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.drop_column('probe_source')

    # ### end Alembic commands ###
