"""scenario investigation snapshots

Revision ID: c50a6285ba21
Revises: 73eb7f3ce327
Create Date: 2026-09-02 19:26:15.925345

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c50a6285ba21'
down_revision: Union[str, Sequence[str], None] = '73eb7f3ce327'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('investigations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('access_control_scenario_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('access_control_snapshot', sa.JSON(), nullable=False, server_default='{}'))
        batch_op.create_index(batch_op.f('ix_investigations_access_control_scenario_id'), ['access_control_scenario_id'], unique=False)
        batch_op.create_foreign_key(
            'fk_investigations_access_control_scenario_id',
            'access_control_scenarios',
            ['access_control_scenario_id'],
            ['id'],
            ondelete='SET NULL',
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('investigations', schema=None) as batch_op:
        batch_op.drop_constraint('fk_investigations_access_control_scenario_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_investigations_access_control_scenario_id'))
        batch_op.drop_column('access_control_snapshot')
        batch_op.drop_column('access_control_scenario_id')

    # ### end Alembic commands ###
