"""recon queue tracking

Revision ID: f506a7d2d209
Revises: 06e592667402
Create Date: 2026-09-01 17:04:36.488187

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f506a7d2d209'
down_revision: Union[str, Sequence[str], None] = '06e592667402'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recon_jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('queue_job_id', sa.String(length=100), nullable=True))
        batch_op.create_index(batch_op.f('ix_recon_jobs_queue_job_id'), ['queue_job_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recon_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recon_jobs_queue_job_id'))
        batch_op.drop_column('queue_job_id')

    # ### end Alembic commands ###
